import Head from "next/head";
import { useAppDispatch, useAppSelector } from "../app/Hook";
import { authAction } from "../app/splice/authSlipe";
import styles from "../styles/Home.module.css";

export default function Home() {
  const ditpatch = useAppDispatch();
  const islogin = useAppSelector((state) => state.auth.login);

  const click = () => {
    ditpatch(authAction.login());
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 onClick={click}>cliskme</h1>
      {islogin && <h1>login....</h1>}
    </div>
  );
}
